# Use an image with Python installed
FROM python:latest

# Copy the source code into the container
COPY hello.py /app/hello.py

# Set the working directory
WORKDIR /app

# Run the Python script
CMD ["python", "hello.py"]
